### ISSUE TITLE
Do you have a copy of the train/dev/test splits?

### ISSUE THREAD

**Issue by reiinakano** [princeton-nlp/WebShop#1]
Hello! I may have missed it in the paper and repo but do you have a copy of the samples within your train/dev/test splits? It might be good for us to use the same test split so our results are more comparable to yours. Thank you!

**Comment by howard50b** [comment]
Ah thanks for pointing this out! Will include that right away.

**Comment by ysymyth** [comment]
Hi, after loading text env goals and shuffle here:
https://github.com/princeton-nlp/WebShop/blob/61e56dbba107ae13ff49e6058d7d2aad23326929/web_agent_site/envs/web_agent_text_env.py#L305

the first 500 goals are test, next 1000 are eval, and the rest are train. Thanks for asking!

        if split == 'test':
            goal_idxs = range(500)
        elif split == 'eval':
            goal_idxs = range(500, 1500)
        elif split == 'train':
            goal_idxs = range(1500, len(env.server.goals))

**Comment by sgdgp** [comment]
@ysymyth 
In `train_search_il.py` following is the train-val-test split:

```
if split == 'train':
   goal_range = range(500, len(human_goals))
elif split == 'validation':
   goal_range = range(500, 1500)
elif split == 'test':
   goal_range = range(0, 500)
```

This is wrong I guess then? for train it should be from 1500 in this script?
