### ISSUE TITLE
Missing Trajectory Annotations

### ISSUE THREAD

**Issue by ANarayan** [princeton-nlp/WebShop#14]
Hi!

In the paper you mentioned that you collected over 1,600 human demonstrations. I was looking through the data and believe that these trajectories are the ones stored here: https://drive.google.com/drive/u/1/folders/16H7LZe2otq4qGnKw_Ic1dkt-o3U9Zsto.

However, when I look at the individual files, I do not see the trajectory annotations such as click [buy now], click [next], search etc. 

The trajectory files look as follows:
![image](https://user-images.githubusercontent.com/5660075/205727841-b95fd1bb-c2d0-4c61-9ae1-bfc3735a2b19.png)

**Comment by howard50b** [comment]
Hi @ANarayan, 
Sorry for the confusion. The files in the folder only log the states and require a conversion step to generate the actions. We have the finalized conversion file [here](https://github.com/princeton-nlp/WebShop/blob/master/baseline_models/data/il_trajs_finalized_images.zip).
Hope this helps!

**Comment by howard50b** [comment]
I'll close the issue for now. Feel free to reopen if there's any further questions!
