### ISSUE TITLE
Some product attributes can't be found in product info

### ISSUE THREAD

**Issue by sanxing-chen** [princeton-nlp/WebShop#16]
It seems that curtain products contain attributes that can't be found anywhere in the product's info (title, descriptions). In the example attached, attributes `nylon spandex` and `machine wash` can't be found.

[B071CPPYMC.txt](https://github.com/princeton-nlp/WebShop/files/10201167/B071CPPYMC.txt)

**Comment by howard50b** [comment]
It seems that the attributes are mined using the `small_description_old` field in the `items_shuffle.json` file. At one point we updated `small_description_old` to `small_description` and maybe that's where this discrepancy occurs.
