### ISSUE TITLE
How can I get the product image urls in baseline_models/data/il_trajs_finalized_images.jsonl?

### ISSUE THREAD

**Issue by pooruss** [princeton-nlp/WebShop#18]
hi~ How can I get the image urls of the products in baseline_models/data/il_trajs_finalized_images.jsonl? 

I tried to look in the items_shuffle.json, but did not match any using the asin id.

**Comment by ysymyth** [comment]
Hi, have you tried to run these actions using the environment, so that you can get all information from the environment object (e.g. what product page is currently is)?

**Comment by ysymyth** [comment]
I'll close for now but feel free to open a new one.
