### ISSUE TITLE
when I run test.py, shows missing feat_conv.pt

### ISSUE THREAD

**Issue by sfengsph** [princeton-nlp/WebShop#19]
When I run test.py under baseline model directory, it was complaining "/data/feat_conv.pt" not found. Would it be possible to share this file together with the feat_ids.pt file? Thanks.

**Comment by ysymyth** [comment]
Hi, check out readme setup step 7. You need to download these from https://drive.google.com/drive/u/2/folders/1jglJDqNV2ryrlZzrS0yOEk-aRAcLAhNw
