### ISSUE TITLE
Duplicates in instructions?

### ISSUE THREAD

**Issue by reiinakano** [princeton-nlp/WebShop#2]
Unless I did something wrong I think you have some duplicates in your 12,087 instruction set.

I found 498 duplicates in the `goals` list in `app.py`

**Comment by howard50b** [comment]
Thanks for reaching out! Do you mean 498 duplicated `asin`'s or exact texts?

**Comment by reiinakano** [comment]
Ah, I mean duplicate product instructions `product["instruction"]` e.g. In https://github.com/princeton-nlp/WebShop/blob/master/web_agent_site/engine/goal.py#L54 if you don't add in the randomly generated `price_text`

**Comment by ysymyth** [comment]
I think it's because for the same product we may have collected more than one human instruction -- Is that what you mean by "duplicates"?

**Comment by reiinakano** [comment]
I mean something like 

goal.py
```
            goals.append({
                'asin': asin,
                'category': item['category'],
                'query': item['query'],
                'name': item['name'],
                'product_category': item['product_category'],
                'instruction': product['instruction'],   # <<---------------------------- I added this line
                'instruction_text': product['instruction'].strip('.') + price_text,
                'attributes': attributes,
                'price_upper': price_upper,
                'goal_options': product['instruction_options'],
            })
```

app.py
```
        goals = get_goals(all_products, product_prices)

        goal_text_to_goal = {goal["instruction"]: goal for goal in goals}
        print(f"Found {len(goals) - len(goal_text_to_goal)} / {len(goals)} duplicates. Total {len(goal_text_to_goal)} goals")
```

returns `Found 11589 / 12087 duplicates. Total 498 goals`

(Please let me know also if I'm misinterpreting something, I'm not too familiar with the codebase.)

**Comment by ysymyth** [comment]
All human instructions are in https://github.com/princeton-nlp/WebShop/blob/master/baseline_models/data/human_goals.json and there shouldn't be just 498 different ones. Can you check the key value pairs of your `goal_text_to_goal` again and compare with the json?

**Comment by reiinakano** [comment]
Sorry, I switched the numbers around in my last comment, should've been `Found 498 / 12087 duplicates. Total 11589 goals`

Thanks for uploading the data. 

```python
import requests
import json
resp = requests.get("https://raw.githubusercontent.com/princeton-nlp/WebShop/master/baseline_models/data/human_goals.json")
d = json.loads(resp.text)
print(len(d), len(set(d)))
```
prints `12087 11563` (which is a little off my initial calculation for some reason)

**Comment by howard50b** [comment]
Hi, after some checking we see that indeed there are some duplicates as you described. We are looking into where it starts to permeate from the raw files. Thanks for raising this!
