### ISSUE TITLE
Live site is down?

### ISSUE THREAD

**Issue by shenao-zhang** [princeton-nlp/WebShop#20]
It seems the live site can't be accessed. I've tried multiple devices and VPNs.

**Comment by ysymyth** [comment]
Hi, we closed it for now as it's costing $200 per month on AWS. We will work on some alternative solution soon.

**Comment by shenao-zhang** [comment]
Oh I see. Is there any scheduled plan? Webshop seems to be a perfect testbed for our project.

**Comment by ysymyth** [comment]
we are figuring out re-hosting it in a Princeton server, hopefully can be done soon!

**Comment by SuhongMoon** [comment]
Any update on this?

**Comment by huayicong23** [comment]
Same question.Any updates now?

**Comment by Graystripe17** [comment]
Hugging face space is down. Any update?

**Comment by yanan1116** [comment]
any updates ?

**Comment by ysymyth** [comment]
We probably won't host live sites due to cost issues for now. Will update if things change.
