### ISSUE TITLE
Human Demonstration Dateset

### ISSUE THREAD

**Issue by yuchen-x** [princeton-nlp/WebShop#21]
Hi, 

Would it be possible to publish the 1600 human demonstration data? Thank you!

**Comment by howard50b** [comment]
Hi, sorry for the late reply. Human demonstration data can be downloaded [here](https://drive.google.com/file/d/1GWC8UlUzfT9PRTRxgYOwuKSJp4hyV1dp/view?usp=sharing). Let me know if there's further question!

**Comment by yuchen-x** [comment]
Thank you so much for the sharing!

**Comment by yuchen-x** [comment]
Thank you very much for your earlier response!

I looked into the jsonl files and realized that the format was different from the log of your ReAct code (WebShop.ipynb), for instance, I didn't detect the corresponding "action" in the demo trajectories. I was wondering if you already had any parser to transfer the human demonstrations into the format as the log of your ReAct code. If you could share the parser with us, that would be greatly helpful and appreciated!

Thank you, again!

**Comment by Anticope12** [comment]
following

**Comment by yuchen-x** [comment]
@howard50b Just a reminder, and look forward to hearing from you soon! Thank you so much!
