### ISSUE TITLE
Missing "action" information in demonstration data

### ISSUE THREAD

**Issue by srsohn** [princeton-nlp/WebShop#27]
Hi,

I looked into the demonstration data jsonl files and I could not find the "action" information in the demo trajectories. If you could provide some help on locating the action information, it would be very helpful! There is a similar issue raised by @yuchen-x but seems it was closed before being answered. So just wanted to resurface it. 

FYI: the old issue by @yuchen-x:
"""
              Thank you very much for your earlier response!

I looked into the jsonl files and realized that the format was different from the log of your ReAct code (WebShop.ipynb), for instance, I didn't detect the corresponding "action" in the demo trajectories. I was wondering if you already had any parser to transfer the human demonstrations into the format as the log of your ReAct code. If you could share the parser with us, that would be greatly helpful and appreciated!

Thank you, again!

_Originally posted by @yuchen-x in https://github.com/princeton-nlp/WebShop/issues/21#issuecomment-1687233290_
"""

**Comment by ysymyth** [comment]
Sorry, I may have lost the code somewhere in Google codebases... Feel free to open new issues for more concrete help if you try it yourself and face issues.
