### ISSUE TITLE
1000 products, but no product is found

### ISSUE THREAD

**Issue by monilouise** [princeton-nlp/WebShop#29]
## I'm submitting a ...

- [X] bug report
- [ ] feature request

## What is the current behavior?

When I run the random policy or even step an action manually (eg.: search by shoes, a very common product), no product is found.  I tried with other strings (bags, durable, jumpsuits), but no product works.

### Steps to Reproduce

env.reset()
env.step('search[shoes]')

## What is the expected behavior?

At least one product should be returned in the search results, but it always returns "(Total results: 0)"

## Please tell us about your environment:

Both Google Colab and Linux.

**Comment by huayicong23** [comment]
> ## I'm submitting a ...
> * [x]  bug report
> * [ ]  feature request
> 
> ## What is the current behavior?
> When I run the random policy or even step an action manually (eg.: search by shoes, a very common product), no product is found. I tried with other strings (bags, durable, jumpsuits), but no product works.
> 
> ### Steps to Reproduce
> env.reset() env.step('search[shoes]')
> 
> ## What is the expected behavior?
> At least one product should be returned in the search results, but it always returns "(Total results: 0)"
> 
> ## Please tell us about your environment:
> Both Google Colab and Linux.

Hi,I encounter the same problem as you.I set DEBUG_PROD_SIZE=100000,still no results found.Have you solved it?

**Comment by ysymyth** [comment]
did you follow all setup steps in the readme.md? e.g. `> ./setup.sh [-d small|all]`

**Comment by huayicong23** [comment]
> did you follow all setup steps in the readme.md? e.g. `> ./setup.sh [-d small|all]`
Thanks for your reply!I follow the setup steps in the readme.md.The reason why no products are found is that the indexes in search engine directory aren't buillt.After I run the convert_product_file_format.py,products returned correctly.

**Comment by ysymyth** [comment]
glad it got resolved!
