### ISSUE TITLE
Doubt about training data

### ISSUE THREAD

**Issue by sgdgp** [princeton-nlp/WebShop#3]
Hi,

In the readme for baseline model it is mentioned to unzip some training data : `unzip il_trajs_finalized_images.zip`.

This was not download as part of `./setup.sh`. Could you provide the download link for this?

**Comment by sgdgp** [comment]
I got that training data in `baseline_models/data`. However on calling the test script it asks for `feat_conv.pt`. If there is a pre-trained version for this could it be made available?

**Comment by ysymyth** [comment]
Hi, I've just uploaded the README.md and check setup item 7. Thanks!
