### ISSUE TITLE
[Installation Issues] - Arm-based Mac (M1, M2, M3); faiss-cpu; Werkzeug.urls, spacy

### ISSUE THREAD

**Issue by ai-nikolai** [princeton-nlp/WebShop#33]
## Various Installation Issues (especially on arm-based mac).
- [ X ] bug report

## What is the current behavior?
- Currently installation following the README file is not possible on arm-based mac (not sure about other environments, but **suspect some errors are cross platform**).

### Steps to Reproduce
```bash
./setup.sh
```

## What is the expected behavior?
It should install OOB on arm-based Mac (and other platforms).

## Motivation for Change

Not installing properly and so not usable.

## Please tell us about your environment:

- MacOS 14
- arm-based chip

**Comment by ai-nikolai** [comment]
@karthikncode @CodeCreator @danqi @ysymyth - this PR is a fix to the above problem (and probably fixes on other envs as well).

PR that fixes the issue:
https://github.com/princeton-nlp/WebShop/pull/34

**The changes are documented in README_INSTALL_ARM_MAC.md**.

In addition changed: `download en_core_web_lg` to `download en_core_web_sm` (as `download en_core_web_lg` is probably slightly deprecated on Spacy's side and is taking ages to download.) if a more powerful model is needed I would recommend: `download en_core_web_trf`.

**Comment by ysymyth** [comment]
thank you! have merged.

**Comment by ai-nikolai** [comment]
@ysymyth thanks for merging. As mentioned in the comment above in the PR:

I changed: `download en_core_web_lg` to download `en_core_web_sm` (as download `en_core_web_lg` is probably slightly deprecated on Spacy's side and is taking ages to download.) if a more powerful model is needed I would recommend: download `en_core_web_trf`.

What do you think?
