### ISSUE TITLE
the hosted version / build from source does not work

### ISSUE THREAD

**Issue by nischalj10** [princeton-nlp/WebShop#38]
## I'm submitting a ...

- [X] bug report
- [ ] feature request

## What is the current behavior?

the hosted version at http://3.83.245.205:3000/pnlp does not load. when trying to build from source, nsmlib and pyyaml are causing issues while installation in the conda env. 

### Steps to Reproduce

following the steps in `README_INSTALL_ARM_MAC.md` on an M2 MacBook 

## What is the expected behavior?

either the hosted version or build from source should work.

**Comment by ysymyth** [comment]
our live site is down for now due to maintainance cost, sorry. we'll remove it from our homepage for now.
