### ISSUE TITLE
ModuleNotFoundError: No module named 'web_agent_site' for Python package

### ISSUE THREAD

**Issue by lewtun** [princeton-nlp/WebShop#39]
## I'm submitting a ...

- [x] bug report
- [ ] feature request

## What is the current behavior?

I am trying to run `webshop` via the [Python package](https://pypi.org/project/webshop/) on `pip`. The installation seems to work fine, but afterwards I am not able to import `WebAgentTextEnv` due to the following error:

```
ModuleNotFoundError: No module named 'web_agent_site'
```

### Steps to Reproduce

Run `pip install webshop` followed by

```python
import gym
from web_agent_site.envs import WebAgentTextEnv
```

## What is the expected behavior?

That I can import the `WebAgentTextEnv` as described in the usage section of the README.

## Motivation for Change

I would like to integrate `WebAgentTextEnv` within my own training scripts and installing everything from source is a big hassle due to dependency conflicts and manual downloads. It would be great to have the Python package dependencies setup so that it is the exact minimum needed to use the environment

## Please tell us about your environment:

* Version: 0.1.0
* Browser: N/A
* Language: N/A

**Comment by nischalj10** [comment]
I am unable to install websop package through pip. can you share your env details?

**Comment by ysymyth** [comment]
can you try if local install via readme works? pip might be maintain overdued

**Comment by lewtun** [comment]
Yes I can confirm the local install works. Perhaps it makes sense to remove the `pip` part of the README if there's no plan to update it?

**Comment by ysymyth** [comment]
removed!
