### ISSUE TITLE
FileURLRetrievalError when installing

### ISSUE THREAD

**Issue by JiinKim0102** [princeton-nlp/WebShop#46]
## I'm submitting a ...

- [O] bug report
- [ ] feature request

## What is the current behavior?

I've encountered this error, which is already a closed issue. 

```
gdown.exceptions.FileURLRetrievalError: Failed to retrieve file url:

        Cannot retrieve the public link of the file. You may need to change
        the permission to 'Anyone with the link', or have had many accesses.
        Check FAQ in https://github.com/wkentaro/gdown?tab=readme-ov-file#faq.

You may still be able to access the file from the browser:

        https://drive.google.com/uc?id=1PD_85XrMIq3ZgJF4sK3e0Ot3jR6J7Vkz

but Gdown can't. Please check connections and permissions.
Downloading example trajectories complete
```
Could you fix it?

### Steps to Reproduce

./setup.sh -d all
and 
./setup.sh -d small

## Please tell us about your environment:

* Version:
* Browser:
* Language:

**Comment by taogoddd** [comment]
I think this might be related to Google's request frequency limitation but the link is still valid. I also met this problem. But I manually download the folder and send it to the server through scp. This should fix it but a little bit more time-consuming.

**Comment by JiinKim0102** [comment]
Thank you!
