### ISSUE TITLE
Are the Amazon URLs for images stored somewhere?

### ISSUE THREAD

**Issue by reiinakano** [princeton-nlp/WebShop#5]
I've noticed that your images are in the form of Amazon URLs like https://m.media-amazon.com/images/I/41npPuaBBYL.jpg

I'm wondering if you have a downloaded scrape of these images stored somewhere for future-proofing. If not, I can imagine a future when these images start getting removed from Amazon, and this eval would be irreparable at that point (at least the images).

**Comment by howard50b** [comment]
I believe we have the images cached. @ysymyth that's the case right?

**Comment by ysymyth** [comment]
We have cached ResNet image features (see README) for model running but not images. There are millions of images and downloading them all could take much more space, but like you said would be a good idea for future-proofing. We will look into if this is possible.
